export const Users = [
    {
        "id":1,
        "first_name":"Jaya",
        "last_name":"Krishna",
        "email":"jayakrishna@gmail.com",
        "gender":"male"
    },
    {
        "id":2,
        "first_name":"Hari",
        "last_name":"Krishna",
        "email":"harikrishna@gmail.com",
        "gender":"male"
    },
    {
        "id":3,
        "first_name":"Rani",
        "last_name":"Kumari",
        "email":"ranikumari@gmail.com",
        "gender":"female"
    },
    {
        "id":4,
        "first_name":"Ramesh",
        "last_name":"Krishna",
        "email":"rameshkrishna@gmail.com",
        "gender":"male"
    },
    {
        "id":5,
        "first_name":"Ramesh",
        "last_name":"Babu",
        "email":"rameshbabu@gmail.com",
        "gender":"male"
    },
    {
        "id":6,
        "first_name":"Rani",
        "last_name":"Kumari",
        "email":"ranikumari@gmail.com",
        "gender":"female"
    },
    {
        "id":7,
        "first_name":"Mukesh",
        "last_name":"Krishna",
        "email":"mukeshkrishna@gmail.com",
        "gender":"male"
    },
    {
        "id":8,
        "first_name":"Jaya",
        "last_name":"lakshmi",
        "email":"jayalakshmi@gmail.com",
        "gender":"female"
    },
    {
        "id":9,
        "first_name":"Jay",
        "last_name":"Krishna",
        "email":"jaykrishna@gmail.com",
        "gender":"male"
    },
    {
        "id":10,
        "first_name":"kalyan",
        "last_name":"Babu",
        "email":"kalyanbabu@gmail.com",
        "gender":"male"
    },
    {
        "id":11,
        "first_name":"Mahesh",
        "last_name":"Babu",
        "email":"maheshbabu@gmail.com",
        "gender":"male"
    },
    {
        "id":12,
        "first_name":"Ramana",
        "last_name":"",
        "email":"ramana@gmail.com",
        "gender":"female"
    },
    {
        "id":13,
        "first_name":"kalyani",
        "last_name":"",
        "email":"kalyani@gmail.com",
        "gender":"female"
    },
    {
        "id":14,
        "first_name":"Raja",
        "last_name":"Rao",
        "email":"rajarao@gmail.com",
        "gender":"male"
    }
]